FROM node:18-alpine AS builder

WORKDIR /app

COPY zebrra_mail_panel/package*.json ./
RUN npm install

COPY zebrra_mail_panel/ ./
RUN npm run build

RUN ls -la /app/dist

FROM nginx:alpine

COPY docker/nginx.front.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]