name: CI/CD Pipeline

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        name: Build Docker Images Locally
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build Front image locally
              run: |
                docker build -t mailpanel:latest -f docker/Dockerfile.front .

    deploy:
        name: Deploy to VPS
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.2.2
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USER }}
                key: ${{ secrets.VPS_SSH_KEY }}
                port: 2222
                script: |
                  cd /home/admin/ZebrraMainPanel
                  git pull
                  cd docker
                  docker-compose -p mailpanel down
                  docker-compose -p mailpanel build --no-cache
                  docker-compose -p mailpanel up -d
                  docker system prune -f